### ISSUE TITLE
Implement Job Posting Functionality

### ISSUE THREAD

**Issue by AhmedFatthy1040** [activecourses/upwork-clone-backend#37]
#### Issue Description:
As a client, I want to be able to post new job listings on the platform so that freelancers can view and apply for them. This functionality should ensure that all necessary job details are collected and stored in the database.

#### Tasks:
1. Create an endpoint in the **JobController** for clients to post new job listings.
2. Define the required fields for job postings, aligning with the database schema:
   - **client_id**: ID of the client (automatically derived from the authenticated user's context)
   - **title**: Job title (required)
   - **description**: Job description (required)
   - **budget**: Job budget (optional)
   - **job_type**: Job type (must be either "Hourly" or "Fixed", required)
   - **status**: Initial status of the job (default to "Open", required)
   - **created_at**: Timestamp (automatically set to the current timestamp)
3. Implement validation to ensure all required fields are provided and meet the necessary criteria.
4. Store the job details in the database using the defined schema.
5. Implement error handling to return meaningful messages for invalid data.

#### Acceptance Criteria:
- [ ] Clients should be able to make a `POST` request to `/jobs` to create a new job listing.
- [ ] Return **201 Created** if the job is posted successfully.
- [ ] Return **400 Bad Request** if any required fields are missing or invalid.
- [ ] Ensure proper error handling and validation messages.
- [ ] Job postings should be stored in the database and retrievable through the **Get All Jobs** endpoint.

#### Endpoint Specification:
- **Method**: `POST`
- **URL**: `/jobs`
- **Request Body Example**:
    ```json
    {
      "title": "Web Developer Needed",
      "description": "Looking for an experienced web developer to create a website.",
      "budget": 500.00,
      "job_type": "Fixed"
    }
    ```
- **Response Example** (Success - 201 Created):
    ```json
    {
      "message": "Job posted successfully",
      "jobId": 12345
    }
    ```
- **Response Example** (Invalid Data - 400):
    ```json
    {
      "error": "Job title is required"
    }
    ```
