### ISSUE TITLE
Implement Job Status Management Functionality

### ISSUE THREAD

**Issue by AhmedFatthy1040** [activecourses/upwork-clone-backend#40]
#### Issue Description:
As a client, I want to manage the status of my job postings so that I can track the progress of each job and update their statuses accordingly. This functionality should allow clients to change the status of their jobs based on their current state.

#### Tasks:
1. **Update Job Status**:
   - Create an endpoint in the **JobController** to allow clients to update the status of their job postings.
   - The status should be limited to the following options:
     - `Open`
     - `In Progress`
     - `Completed`
     - `Cancelled`

2. **Get Job Status**:
   - Create an endpoint to retrieve the current status of a specific job based on the job ID.

#### Acceptance Criteria:
- **Update Job Status**:
  - [ ] Clients should be able to make a `PUT` request to `/jobs/{jobId}/status` to update the job status.
  - [ ] Return **200 OK** if the update is successful or **404 Not Found** if the job does not exist.
  - [ ] Return **400 Bad Request** if the provided status is invalid.

- **Get Job Status**:
  - [ ] Clients should be able to make a `GET` request to `/jobs/{jobId}/status` to retrieve the current status of the job.
  - [ ] Return **200 OK** with the job status or **404 Not Found** if the job does not exist.

#### Endpoint Specifications:
- **Update Job Status**:
  - **Method**: `PUT`
  - **URL**: `/jobs/{jobId}/status`
  - **Request Body Example**:
    ```json
    {
      "status": "Completed"
    }
    ```

- **Get Job Status**:
  - **Method**: `GET`
  - **URL**: `/jobs/{jobId}/status`
