### ISSUE TITLE
Implement Admin Job Management Functionality

### ISSUE THREAD

**Issue by AhmedFatthy1040** [activecourses/upwork-clone-backend#42]
#### Issue Description:
As an admin, I want to manage job postings on the platform so that I can ensure compliance with the community guidelines and maintain the quality of job listings. This functionality should allow admins to view, update, and delete job postings as necessary.

#### Tasks:
1. **View All Jobs**:
   - Create an endpoint to allow admins to view all job postings in the system, including relevant details such as job title, client ID, status, and creation date.

2. **Update Job Details**:
   - Create an endpoint to allow admins to update the details of a specific job posting, including:
     - Job title
     - Description
     - Budget
     - Job type
     - Status

3. **Delete Job Posting**:
   - Create an endpoint to allow admins to delete a specific job posting by its ID.

4. **Get Job Details**:
   - Create an endpoint for admins to retrieve detailed information about a specific job posting.

#### Acceptance Criteria:
- **View All Jobs**:
  - [ ] Admins should be able to make a `GET` request to `/admin/jobs` to retrieve all job postings.
  - [ ] Return **200 OK** with a list of jobs or **204 No Content** if no jobs are available.

- **Update Job Details**:
  - [ ] Admins should be able to make a `PUT` request to `/admin/jobs/{jobId}` to update job details.
  - [ ] Return **200 OK** if the update is successful or **404 Not Found** if the job does not exist.

- **Delete Job Posting**:
  - [ ] Admins should be able to make a `DELETE` request to `/admin/jobs/{jobId}` to remove a job posting.
  - [ ] Return **204 No Content** if the deletion is successful or **404 Not Found** if the job does not exist.

- **Get Job Details**:
  - [ ] Admins should be able to make a `GET` request to `/admin/jobs/{jobId}` to retrieve job details.
  - [ ] Return **200 OK** with job details or **404 Not Found** if the job does not exist.

#### Endpoint Specifications:
- **View All Jobs**:
  - **Method**: `GET`
  - **URL**: `/admin/jobs`

- **Update Job Details**:
  - **Method**: `PUT`
  - **URL**: `/admin/jobs/{jobId}`
  - **Request Body Example**:
    ```json
    {
      "title": "Updated Job Title",
      "description": "Updated job description.",
      "budget": 150.00,
      "job_type": "Hourly",
      "status": "Open"
    }
    ```

- **Delete Job Posting**:
  - **Method**: `DELETE`
  - **URL**: `/admin/jobs/{jobId}`

- **Get Job Details**:
  - **Method**: `GET`
  - **URL**: `/admin/jobs/{jobId}`
